### ISSUE TITLE
MSRVTT dataset

### ISSUE THREAD

**Issue by BlueCat7** [ArrowLuo/CLIP4Clip#1]
Dear author, thanks your work. When I download MSRVTT dataset, there are some urls broken. How do you solve it, thanks.

**Comment by ArrowLuo** [comment]
@BlueCat7 
The videos are fine when we download them. 
It is a normal issue encountering urls broken. Keep the same test split is enough to make the comparison fair. I think it is ok if the missing ratio is low.

**Comment by BlueCat7** [comment]
Thank you for your quick response to my issue. But I miss about 2 thousand videos, maybe it's a problem to training.

**Comment by ArrowLuo** [comment]
It is indeed a problem. Do you check the original URL? Is the linked video removed? If this is the case, you can check the overlap between the training (MSRVTT_train.9k.csv or MSRVTT_train.7k.csv), test splits (MSRVTT_JSFUSION_test.csv), and your downloaded videos. How much they lost respectively?

**Comment by BlueCat7** [comment]
Ok, I will check it firstly, thanks.

**Comment by ArrowLuo** [comment]
If you want to compare the results with baselines including ours, you can rerun the baselines on your dataset. To CLIP4Clip, replace `MSRVTT_train.9k.csv or MSRVTT_train.7k.csv` and `MSRVTT_JSFUSION_test.csv` with yours CSV will be okay. It is a compromise though will cost a long time.

**Comment by BlueCat7** [comment]
Ok, thank you for your suggestion.
