### ISSUE TITLE
running the project

### ISSUE THREAD

**Issue by giraffeooo** [ArrowLuo/CLIP4Clip#103]
Sorry to bother you,I wonder why this problem arises。 

-INFO- Weight doesn't exsits./home/workspace/CLIP4CLip-master/modUles/cross-base/cross_pytorch_model.bin     
-INFO- Weights from pretrained model not used in CLIP4Clip: 
clip.input_resolution
clip.context_length
clip.vocab_size"

What's more，I don't see the config of cross_pytorch_model.bin in the README.I am a complete beginner in deep learning,waiting for your answering，thanks！

**Comment by HU-xiaobai** [comment]
@giraffeooo hello sorry to bother you, do you know where to download the model weight for clip4clip now? I have not found it, thanks!
