### ISSUE TITLE
Problem about reproducing the model

### ISSUE THREAD

**Issue by sweet132** [ArrowLuo/CLIP4Clip#104]
meanP

[meanP.txt](https://github.com/ArrowLuo/CLIP4Clip/files/11705891/meanP.txt)

seqTransf
[Transf.txt](https://github.com/ArrowLuo/CLIP4Clip/files/11705892/Transf.txt)

Sorry to bother you, I have run the code directly, but the loss is NaN since some wrong videos(the solution is to set the video to 0 in the provided code).
If I modify the code about video process, I don't know why I can only get 42.3% for meanP and 43.9% for seqTransf.

How can you get 43.1%?  Have you modified the code for data processing ?

**Comment by laoniandisko** [comment]
> 

How did you solve your problem?
