### ISSUE TITLE
Weight decay 

### ISSUE THREAD

**Issue by FuTSy13** [ArrowLuo/CLIP4Clip#11]
Hello! Is it OK that you apply weight decay to no_decay params group and do not apply to decay params group at https://github.com/ArrowLuo/CLIP4Clip/blob/master/main_task_retrieval.py#L202 ?

**Comment by ArrowLuo** [comment]
Hi @FuTSy13. Sorry that the wrong variable names make some misunderstand. I have renamed them. Thanks.
