### ISSUE TITLE
cap.set(cv2.CAP_PROP_POS_FRAMES, sec_base + ind) gets some h264 warning message

### ISSUE THREAD

**Issue by cheetah003** [ArrowLuo/CLIP4Clip#15]
Hi,
When I run Clip4Clip code to exact video frames, this code in rawvideo_utils.py:cap.set(cv2.CAP_PROP_POS_FRAMES, sec_base + ind),print some warning message like:
[h264 @ 0x56543b236ac0] illegal short term buffer state detected
[h264 @ 0x5654397996c0] Missing reference picture, default is 0
[h264 @ 0x5654397996c0] decode_slice_header error

[h264 @ 0x56543aefc800] Invalid NAL unit size (30588 > 15033).
[h264 @ 0x56543aefc800] Error splitting the input into NAL units.

Did you met this before?  Not sure whether this have effect on frames that we extracted...

**Comment by ArrowLuo** [comment]
Hi @cheetah003,
I have not such warnings. You can do a unit test on the frame extraction to eliminate the problem. Is something wrong with the raw video or the running environment?

**Comment by cheetah003** [comment]
Hi @ArrowLuo ，
I have test on the msrvtt video, and find no warnings. Maybe there is something wrong with the raw video that I used. Thanks~
