### ISSUE TITLE
Some question about using WebVid dataset.

### ISSUE THREAD

**Issue by Wanan-ni** [ArrowLuo/CLIP4Clip#18]
Thanks for sharing your code. I wonder if you can share the WIT dataset.  When you pre-training on WIT dataset,  the setting of hyper-parameters are similar to training datasets?

**Comment by ArrowLuo** [comment]
Hi @Wanan-ni, WIT is not proposed by us. It is the pertained data in [CLIP](https://arxiv.org/pdf/2103.00020.pdf) .

**Comment by Wanan-ni** [comment]
I got it , thanks
