### ISSUE TITLE
Reprocessing the input frames before CLIP/VIT

### ISSUE THREAD

**Issue by menatallh** [ArrowLuo/CLIP4Clip#20]
Please Sir do you normalize the inputs before using the CLIP/VIT to between [-1,1] ? or what do you do ? could you guide me to this part of the code

**Comment by ArrowLuo** [comment]
Hi @menatallh, this model follows CLIP's image transform. You can refer to [here](https://github.com/ArrowLuo/CLIP4Clip/blob/fd833058dcb176d4291861c509c50e6b5fc651f0/dataloaders/rawvideo_util.py#L16) for more information.

**Comment by menatallh** [comment]
i get this error when i try to use it   
![image](https://user-images.githubusercontent.com/73253952/126019271-a8f5322a-33b1-4e3f-bc02-48e59f898a1a.png)

**Comment by ArrowLuo** [comment]
Hi @menatallh, which commad did you carry out. I think this error is caused by cv2. Maybe you can debug on one of your videos to make sure the video can be parsed correctly.
