### ISSUE TITLE
wrong masking for multi-head attention

### ISSUE THREAD

**Issue by junchen14** [ArrowLuo/CLIP4Clip#22]
https://github.com/ArrowLuo/CLIP4Clip/blob/fd833058dcb176d4291861c509c50e6b5fc651f0/modules/module_cross.py#L111

the correct operation is mask_interleave instead of mask

can you please modify this?

**Comment by junchen14** [comment]
Hi @ArrowLuo,  I think the correct way to mask the multihead attention is 
```
attn_mask.repeat_interleave(self.n_head,dim=0)
```

I have also sent a pull request.
actually I tried many experiments with your code and met with this error.

`repeat` function cannot correctly mask all the padding tokens in your setting, and looks like `repeat_interleave` is correct one

and it is also recommended by pytorch official.
<https://github.com/pytorch/pytorch/blob/e6e8745bea8f7e32ff63a13559c710233935cb09/test/test_nn.py#L5075 >

**Comment by ArrowLuo** [comment]
Hi @junchen14, Thank you so much.
