### ISSUE TITLE
How do you sample frames from howto100m videos?

### ISSUE THREAD

**Issue by junchen14** [ArrowLuo/CLIP4Clip#28]
hi,

could you please provide more details regarding how to pretrain on howto100m videos? how you extract frames features? how many frames you extract for each video? how you organize multiple captions of each video (simple concatenation?)

I appreciate it very much

**Comment by ArrowLuo** [comment]
Hi @junchen14, 

I concisely list what you may focus on,

1. Frame extraction: one frame per second
2. 12 frames per clip
3. concatenation and the max token length is 32

The input is the clip instead of the whole video.

Best

**Comment by junchen14** [comment]
hi @ArrowLuo 

I also observe that in howto100m video dataset, there are many overlapping timestamps for the caption, for example, 
322.25,327.11,cool blood dripping
327.11,331.28,black red cool
329.9,333.14,break painting
331.28,336.92,use bongs
333.14,338.93,bubble bath decide wanna
336.92,341.57,fun

did you do any cleanup to remove the overlapping information or just concatenate them all together.

thanks very much

**Comment by ArrowLuo** [comment]
Hi @junchen14, yes, we do some cleanup jobs before concatenate.
