### ISSUE TITLE
MSRVTT dataset

### ISSUE THREAD

**Issue by lyufan** [ArrowLuo/CLIP4Clip#29]
Hi, thanks your work.I want to download MSRVTT dataset, but the link can't open,it display this page can't be used. Could you share some links to download them,thanks!
![image](https://user-images.githubusercontent.com/33341810/133719247-c2795b7f-717c-4b72-8b53-affa69db277d.png)

**Comment by ArrowLuo** [comment]
Hi @lyufan, the official web is unavailable now. We download the dataset by ourselves before that. I can not share the raw dataset in private. But I found Frozen has shared the raw videos. You can find them from [here](https://github.com/m-bain/frozen-in-time#-finetuning-benchmarks-msr-vtt). Thanks to Frozen's sharing for the community.

**Comment by lyufan** [comment]
Thank you for your sharing!
