### ISSUE TITLE
is text vector direct recall videos vector(mean pooling, LSTM, Transformer to generate a video vector)？

### ISSUE THREAD

**Issue by lonngxiang** [ArrowLuo/CLIP4Clip#3]
use mean pooling, LSTM, Transformer to generate a video vector；Does this paper end up as a similar recall of text vector dot videos vector？

_Originally posted by @lonngxiang in https://github.com/ArrowLuo/CLIP4Clip/issues/2#issuecomment-827468848_

**Comment by ArrowLuo** [comment]
Yes. For the loose type, we use vector dot as previous works did.

**Comment by lonngxiang** [comment]
> Yes. For the loose type, we use vector dot as previous works did.

ok，tks

**Comment by lonngxiang** [comment]
is this project only use image features? how about text and audio information?

**Comment by ArrowLuo** [comment]
Hi, the current model can not feed into the audio information.

**Comment by lonngxiang** [comment]
> Hi, the current model can not input the audio information.

ok，thanks for you reply
