### ISSUE TITLE
Query search

### ISSUE THREAD

**Issue by Tortoise17** [ArrowLuo/CLIP4Clip#33]
As I understood correctly, after training and evaluation, videos are set on the basis of ranks and similarity scores. Is there any script available to make a search query as text and get the video with some freedom of search based on confidence or similarity index  with some closest ranked video ?

**Comment by ArrowLuo** [comment]
Feel free to reopen the discussion if needed.

**Comment by Tortoise17** [comment]
> @Tortoise17 good idea, but there is no such implementation in this project.

@ArrowLuo  thank you. If you have any development in that , please let me know as well. Nice work overall.
