### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by JewelChen2019** [ArrowLuo/CLIP4Clip#36]
Hi,  dear Arrow, I have some questions as follow:
1. How to only do evaluation？
2. How to select a model when training on MSRVTT9K or do you just report the results of the final epoch(5th epoch)?

**Comment by ArrowLuo** [comment]
Hi @JewelChen2019,
1. Use `--do_eval` instead of `--do_train` to do evaluate only.
2. Report the best scores according to validation. It needs to uncomment [L546](https://github.com/ArrowLuo/CLIP4Clip/blob/master/main_task_retrieval.py#L546). 

Thanks.
