### ISSUE TITLE
Will this work be published on any conference or transactions?

### ISSUE THREAD

**Issue by FangmingZhou** [ArrowLuo/CLIP4Clip#38]
CLIP4clip is a great work to promote text-video matching, I am curious about whether this work will be submitted to any conference or transactions? Thanks!

**Comment by ArrowLuo** [comment]
Yes, it is under review for a long time. Thanks.

**Comment by FangmingZhou** [comment]
> Yes, it is under review for a long time. Thanks.

Thanks for satisfying my curiosity, good luck to you ~
