### ISSUE TITLE
Resume training from a saved checkpoint

### ISSUE THREAD

**Issue by zara0m** [ArrowLuo/CLIP4Clip#39]
Hello, 

What is the best way to continue training of an epoch from a saved checkpoint of previous epoch?

Thank you

**Comment by ArrowLuo** [comment]
Hi @zara0m, setting the `--init_model` with the saved checkpoint may be a choice, but it is imperfect because the checkpoint has not saved the optimization state. So, the best way is to save and resume the optimization state along with the checkpoint. Thanks.

**Comment by zara0m** [comment]
@ArrowLuo Thanks.

**Comment by aries-young** [comment]
we can use `--init_model` to resume the model from pytorch_model.bin.2, but we resume the pytorch_opt.bin.2, could you please give an specific command instance ?

**Comment by zara0m** [comment]
> 
Use both of them simultaneously to resume training:


--init_model ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.2 \
--resume_model ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_opt.bin.2
