### ISSUE TITLE
Missing Video Problem about DiDeMo

### ISSUE THREAD

**Issue by xmu-xiaoma666** [ArrowLuo/CLIP4Clip#45]
Hello! How can you deal with the missing videos of DiDeMo in [LocalizingMoments](https://github.com/LisaAnne/LocalizingMoments). Missing Videos can not be accessed now.

**Comment by ArrowLuo** [comment]
Hi @xmu-xiaoma666，Did you notice the tip `There are 13 videos which are not on AWS which you may download ...`  at [link](https://github.com/LisaAnne/LocalizingMoments#getting-the-videos)?

**Comment by xmu-xiaoma666** [comment]
> There are 13 videos

Yes, I notice it. But I find that the [link](https://people.eecs.berkeley.edu/~lisa_anne/didemo/data/missing_videos/missing_videos_AWS.zip) can not be accessed now. Can you share the missing 13 videos? Thank you !
![image](https://user-images.githubusercontent.com/33897496/145542933-5123e808-e934-4709-8b99-c14ccdd340a4.png)

**Comment by ArrowLuo** [comment]
Hi @xmu-xiaoma666, I think you should ask for help from the authors of the dataset, thanks.

**Comment by xmu-xiaoma666** [comment]
> Hi @xmu-xiaoma666, I think you should ask for help from the authors of the dataset, thanks.

Thank you,  do you include these 13 missing videos in your training data?

**Comment by ArrowLuo** [comment]
@xmu-xiaoma666, Yes.

**Comment by xmu-xiaoma666** [comment]
> @xmu-xiaoma666, Yes.

Wil you plan to share thses missing 13 videos?

I really can get these 13 videos.

**Comment by ArrowLuo** [comment]
Hi @xmu-xiaoma666, I have no plan to share the videos, and maybe the authors of the dataset can share them with you more conveniently. Thanks.
