### ISSUE TITLE
About splits of LSMDC

### ISSUE THREAD

**Issue by hgzjy25** [ArrowLuo/CLIP4Clip#47]
I found the statistics in LSMDC's readme.txt is following:
= Statistics
- Training: 101,079
- Validation: 7,408
- Public Test: 10,053
- Blind Test: 9,578

But the paper shows 118081 videos and 7408 for validation, why is it different from the above numbers?

**Comment by ArrowLuo** [comment]
Hi @hgzjy25, 118,081 is not the number of the training set, it is the total number of clips. Our training and validation are the same as the official statistics. Thanks.

**Comment by xmu-xiaoma666** [comment]
> I found the statistics in LSMDC's readme.txt is following: = Statistics
> 
> * Training: 101,079
> * Validation: 7,408
> * Public Test: 10,053
> * Blind Test: 9,578
> 
> But the paper shows 118081 videos and 7408 for validation, why is it different from the above numbers?

Hello， can you share LSMDC dataset, I can not download it！

**Comment by ArrowLuo** [comment]
Hi @xmu-xiaoma666, LSMDC can not be shared because of the officially strict rules.

**Comment by xmu-xiaoma666** [comment]
> Hi @hgzjy25, 118,081 is not the number of the training set, it is the total number of clips. Our training and validation are the same as the official statistics. Thanks.

Hello, I find training LSMDC needs files of "LSMDC16_annos_training.csv", "LSMDC16_annos_val.csv" and "LSMDC16_challenge_1000_publictect.csv", where can I find these files?

**Comment by JingXiaolun** [comment]
@xmu-xiaoma666 ， have you reproduced the retrieval results on the LSMDC dataset ?
