### ISSUE TITLE
I can not find "train_data.json","val_data.json","test_data.json"  of didemo dataset,

### ISSUE THREAD

**Issue by xmu-xiaoma666** [ArrowLuo/CLIP4Clip#48]
Hello, I can not find "train_data.json","val_data.json","test_data.json"  of didemo dataset, and it also not be provided in this project. Can you share these files?

**Comment by ArrowLuo** [comment]
Hi @xmu-xiaoma666, feel free to access them in: https://github.com/LisaAnne/LocalizingMoments/tree/master/data
