### ISSUE TITLE
Annotation of ActivityNet

### ISSUE THREAD

**Issue by xmu-xiaoma666** [ArrowLuo/CLIP4Clip#50]
Hello, I can not find "train.json","val_1.json" of activatitynet dataset. Can you share these files?

**Comment by 1240446371** [comment]
i also can not find these json files,please can you provide them to me? sincerely

**Comment by qingkunsu** [comment]
I found this link that may be helpful: https://github.com/gingsi/coot-videotext/tree/master/annotations/activitynet
