### ISSUE TITLE
ActivityNet的损失函数变成nan

### ISSUE THREAD

**Issue by xmu-xiaoma666** [ArrowLuo/CLIP4Clip#54]
感谢您的代码分享，我发现在训练ActivityNet的时候，损失函数会变成nan，请问这个问题怎么解决？

![image](https://user-images.githubusercontent.com/33897496/147379051-6dca464e-3369-4ff6-8b39-a64cb587d05c.png)

**Comment by ArrowLuo** [comment]
@xmu-xiaoma666，it is not an easy problem and needs to debug carefully. If the issue occurred only on this dataset, maybe something was wrong with the dataset. There is no information printed by [line 211](https://github.com/ArrowLuo/CLIP4Clip/blob/master/dataloaders/dataloader_activitynet_retrieval.py#L211) and [line 213], a suggestion is to print some after [line 206] to make sure there is no all zero inputs.

**Comment by xmu-xiaoma666** [comment]
Thanks

**Comment by mboboGO** [comment]
Could you please provide the json data for ActivityNet dataset? I cannot find them.
