### ISSUE TITLE
question about special token "[MASK]"

### ISSUE THREAD

**Issue by ForawardStar** [ArrowLuo/CLIP4Clip#66]
Hello, when want to introduce the Masked Language Modeling (MLM) as the proxy task, the following error ocurred:
`KeyError: '[MASK]'`

So I wonder is this special token unusable? How can I implement MLM? Thanks,

**Comment by ArrowLuo** [comment]
Hi @ForawardStar, there is not a `[MASK]` token in the vocabulary of Text Encoder, so you encountered the error. An approach to doing MLM is to add a learnable parameter to represent the MASK token. Another approach is to add a `[MASK]` token to the vocabulary. Best.
