### ISSUE TITLE
You mentioned in the paper that the GPU is 8 V100, is it 16G or 32G?

### ISSUE THREAD

**Issue by limycml** [ArrowLuo/CLIP4Clip#67]
You mentioned in the paper that the GPU is 8 V100, is it 16G or 32G?
Also, will 1 or 2 A100s (40G) be able to run the code if training speed is not considered?

**Comment by ArrowLuo** [comment]
Hi @limycml, the GPU cost is related to hyper-parameters, e.g., `--max_words` and `--max_frames`. The ActivityNet and DiDeMo need more GPU memory. I think 2 A100s (40G) is enough for `--max_words 32 --max_frames 12` with a small `--batch_size`.  Just try, Best.
