### ISSUE TITLE
How about taking ViViT as video backbone

### ISSUE THREAD

**Issue by aries-young** [ArrowLuo/CLIP4Clip#68]
I find in the paper that your seqTransf model has similar structure with ViViT. So, have you tested the performance of ViViT in retrieval task ？

**Comment by ArrowLuo** [comment]
Hi @aries-young, we did not test with ViViT weight. It is a good idea but may not obtain better performance if training with less paired data.

**Comment by aries-young** [comment]
> Hi @aries-young, we did not test with ViViT weight. It is a good idea but may not obtain better performance if training with less paired data.

Thank you very much for your reply. I'll take a shot.
