### ISSUE TITLE
Question about loss and batch size

### ISSUE THREAD

**Issue by JonnyS1226** [ArrowLuo/CLIP4Clip#69]
hi, thanks that you propose a very nice method and provide a base for many other works.
But i have a question that in your paper and in many other papers based on yours, the batch size means the n_gpu multiple batch_per_gpu. But actually batch_per_gpu is used to calculate InfoNCE loss?
i.e., in your work, the negatives-in-batch is actually 31 not 127? And this cannot be expanded by the method of DDP or Gradient Accumulation?
Thanks!

**Comment by ArrowLuo** [comment]
Hi @JonnyS1226, yes, the calculation of loose similarity adopts `torch.distributed.all_gather` to expand the negatives with the samples in other GPUs, see [here](https://github.com/ArrowLuo/CLIP4Clip/blob/373f3974f9081701894b3aebebaef26d58fe8e08/modules/modeling.py#L387). Best~
