### ISSUE TITLE
Finetuning on custom dataset

### ISSUE THREAD

**Issue by avinashsai** [ArrowLuo/CLIP4Clip#76]
Hi,

I have a text-to-video retrieval dataset I wanted to fine-tune on. Can you suggest where to change the loader and use my dataset?

Thank you.

**Comment by ArrowLuo** [comment]
Hi @avinashsai, plz refer to dataloader_msvd_retrieval.py to organize your dataset. 
The dataloader needs a list to find the path of the video (see [dataloader_msvd_retrieval.py#L43](https://github.com/ArrowLuo/CLIP4Clip/blob/master/dataloaders/dataloader_msvd_retrieval.py#L43) and [dataloader_msvd_retrieval.py#L139](https://github.com/ArrowLuo/CLIP4Clip/blob/master/dataloaders/dataloader_msvd_retrieval.py#L139)), and a caption file (see [dataloader_msvd_retrieval.py#L46](https://github.com/ArrowLuo/CLIP4Clip/blob/master/dataloaders/dataloader_msvd_retrieval.py#L46))
