### ISSUE TITLE
A potential bug in retrieval metric computing

### ISSUE THREAD

**Issue by FangmingZhou** [ArrowLuo/CLIP4Clip#80]
https://github.com/ArrowLuo/CLIP4Clip/blob/master/metrics.py#L14

---

为了方便解释清楚我就使用中文啦～检索指标的计算逻辑是寻找每行中与对角线元素相等的元素的索引，即代码中的ind，但是当一行中存在与对角线相同值的相似度时（概率很小，但测试数据变多后会稳定出现），将会出现ind数量异常（变多），从而导致指标异常

---

The calculation logic of the retrieval index is to find the index of the element in each row that is equal to the diagonal element, but when there is a element of the same value as the diagonal in a row , there will be an abnormal number of inds, resulting in abnormal indicators

**Comment by ArrowLuo** [comment]
Hi @FangmingZhou, yes, maybe you are right. Someone sent me an email about it ago and I noticed it is a potential bug. However, it is an interesting problem when computing the retrieval metric.  I tried to give the below samples,
1.  `x = np.array([[1, 2, 3], [4, 5, 6]])`
 the metrics is `{'R1': 0.0, 'R5': 100.0, 'R10': 100.0, 'MR': 2.5, 'MedianR': 2.5, 'MeanR': 2.5, 'cols': [2, 1]}`

2. `x = np.array([[1, 2, 3], [5, 5, 4]])`
 the metrics is `{'R1': 33.3, 'R5': 100.0, 'R10': 100.0, 'MR': 2.0, 'MedianR': 2.0, 'MeanR': 2.0, 'cols': [2, 0, 1]}`

3. `x = np.array([[1, 2, 3], [5, 5, 5]])`
 the metrics is `{'R1': 25.0, 'R5': 100.0, 'R10': 100.0, 'MR': 2.5, 'MedianR': 2.5, 'MeanR': 2.25, 'cols': [2, 0, 1, 2]}`

4. `x = np.array([[1, 1, 1], [5, 5, 5]])`
 the metrics is `{'R1': 33.3, 'R5': 100.0, 'R10': 100.0, 'MR': 2.0, 'MedianR': 2.0, 'MeanR': 2.0, 'cols': [0, 1, 2, 0, 1, 2]}`

What are the values if the human does such an evaluation? Should case 2 and case 3  have the same metric? Even, will case 4 be 100% for the R1? When there are duplicate similarities, things become complex.  

So, I think the [metrics.py#L14](https://github.com/ArrowLuo/CLIP4Clip/blob/master/metrics.py#L14) is a composite way, which decreases the metric via the denominator `len(ind)` when exiting duplicate similarities. If you want to compare the results, keeping the same calculation is fine, I think.

Best~

**Comment by FangmingZhou** [comment]
Hi 
从你这个例子的这个视角看这个问题确实很有意思～
我也从我的一个角度看一下这个问题（正是我遇到的问题），举个例子🌰：

一个10 query到10 doc的检索任务，通过一次初步的检索过程我获得了每行检索的top2个结果的index，因此再下一次的检索中我只想要计算这两个index位置的相似度（我无法保证groud truth包含在这top2个结果中），其余的值我赋一个特别小的负值：-100。

结果如下：
[[    2,       1,-100,-100,-100,-100,-100,-100,-100,-100,],
[-100,      2,      1,-100,-100,-100,-100,-100,-100,-100,],
[-100,-100,      2,      1-100,-100,-100,-100,-100,-100,],
[-100,-100,-100,      2,      1,-100,-100,-100,-100,-100,],
[-100,-100,-100,-100,      2,      1,-100,-100,-100,-100,],
[-100,-100,-100,-100,-100,      2,      1,-100,-100,-100,],
[-100,-100,-100,-100,-100,-100,      2,      1,-100,-100,],
[-100,-100,-100,-100,-100,-100,-100,      2,      1,-100,],
[-100,-100,-100,-100,-100,-100,-100,-100,      2,      1,],
[      2,      1,-100,-100,-100,-100,-100,-100,-100,-100,],]

前9个检索中，GT都包含在了初步检索结果top2中，但最后一个检索不是。

预期的结果是: R@1: 90.0000 - R@5: 100.0000，
但是现在实现结果是: R@1: 52.9412 - R@5: 70.5882

所以我还是坚持我的观点：以每条query的GT rank作为recall值的计算出发点更加准确，也更加符合recall这个指标的定义

---

It's really interesting to look at this problem from the perspective of your example.
I'm also looking at this problem from my perspective (exactly the problem I'm having), with an example :

For a retrieval task of 10 query to 10 doc, through a preliminary retrieval process, I obtained the index of the top2 results retrieved in each row, so in the next retrieval I only want to calculate the similarity of these two index positions ( I can't guarantee that the ground truth is included in the top2 results), and the rest of the values ​​I assign a particularly small negative value: -100.

The result is as follows:
[[ 2, 1,-100,-100,-100,-100,-100,-100,-100,-100,],
[-100, 2, 1,-100,-100,-100,-100,-100,-100,-100,],
[-100,-100, 2, 1-100,-100,-100,-100,-100,-100,],
[-100,-100,-100, 2, 1,-100,-100,-100,-100,-100,],
[-100,-100,-100,-100, 2, 1,-100,-100,-100,-100,],
[-100,-100,-100,-100,-100, 2, 1,-100,-100,-100,],
[-100,-100,-100,-100,-100,-100, 2, 1,-100,-100,],
[-100,-100,-100,-100,-100,-100,-100, 2, 1,-100,],
[-100,-100,-100,-100,-100,-100,-100,-100, 2, 1,],
[ 2, 1,-100,-100,-100,-100,-100,-100,-100,-100,],]

In the first 9 retrievals, GT was included in the preliminary retrieval results top2, but not in the last retrieval.

The expected result is: R@1: 90.0 - R@5: 100.0,
But now the result is: R@1: 52.9 - R@5: 70.6

So I still stick to my point of view: it is more accurate to use the Ground Truth rank of each query as the basis for the calculation of the recall metric, and it is more in line with the definition of recall.

**Comment by ArrowLuo** [comment]
Hi @FangmingZhou, forgot to reply :), I can not understand why the predicted R@5 should be 100%. But, the below function I wrote previously can obtain R@1 90%, which may be what you need. Best~
``` python
def compute_metrics(x):
    sx = np.argsort(-x, axis=1)
    d = np.array(range(0, x.shape[0]))
    ind = sx - d[:, np.newaxis]
    ind = np.where(ind == 0)[1]
    metrics = {}
    metrics['R1'] = float(np.sum(ind == 0)) * 100 / len(ind)
    metrics['R5'] = float(np.sum(ind < 5)) * 100 / len(ind)
    metrics['R10'] = float(np.sum(ind < 10)) * 100 / len(ind)
    metrics['MR'] = np.median(ind) + 1
    metrics["MedianR"] = metrics['MR']
    metrics["MeanR"] = np.mean(ind) + 1
    metrics["cols"] = [int(i) for i in list(ind)]
    return metrics
```
