### ISSUE TITLE
Batch size issue concerned with Contrastive learning

### ISSUE THREAD

**Issue by celestialxevermore** [ArrowLuo/CLIP4Clip#88]
Dear author, I hope you have a good day.

I have some questions about batch size affects largely on performance.

Q1. 
Though I noticed your experiment within increasing or decreasing batch size like Figure 3 in your paper, 
The larger the batch size, the greater the opportunity for the model to identify more negative samples, so consequently, 
I think the batch size is an important factor in performance in contrast learning, do you agree?

Q2. 
Following the question 1, 
Is that any difference in performance -I guess it is not - if I change the batch size of test dataset?

Thx.

**Comment by ArrowLuo** [comment]
Hi @celestialxevermore,
A1. Yes, the batch size is important for our model.
A2. The results should be the same for different batch sizes when doing the evaluation, ideally.
Best~

**Comment by celestialxevermore** [comment]
Thx, and sorry for my reply being late.
