### ISSUE TITLE
loss NaN  when training on MSRVTT

### ISSUE THREAD

**Issue by TXH-mercury** [ArrowLuo/CLIP4Clip#93]
![image](https://user-images.githubusercontent.com/38175683/208283448-a64af7e3-e47c-47bd-9d00-a724eff74e96.png)

--do_eval can get correct zero-shot performance 
but --do_train meets NaN at the start of training, in both 1 card and 4 cards settings.  The default parameters are used.

**Comment by sweet132** [comment]
Hello, is the problem you said about NaN solved? I also encountered this problem, if I modify the data preprocessing can solve this problem, but the accuracy is not as accurate as in the paper

**Comment by sweet132** [comment]
Hello, is the problem you said about NaN solved? I also meet the problem, if I modify the data preprocessing can solve this problem, but the accuracy is not as accurate as in the paper

**Comment by ZhaiYanbo** [comment]
I encountered the same problem as you. How did you resolve it?
